# 베이스 이미지 선택
FROM fluent/fluentd:v1.14-1

# 필요한 패키지 설치
USER root
RUN apk add --no-cache bash

# Fluentd 설정 파일 복사 및 스크립트 복사
COPY scripts/generate-config.sh /usr/local/bin/generate-config.sh
RUN chmod +x /usr/local/bin/generate-config.sh

# OCI 설정 디렉터리 생성
RUN mkdir -p /root/.oci

# 스크립트를 실행하여 환경 변수 기반으로 설정 파일 생성 및 Fluentd 실행
CMD /usr/local/bin/generate-config.sh