version: '3.8'

services:
  # 애플리케이션 서비스
  app:
    image: now-here-server:latest
    container_name: now-here-server
    ports:
      - "8080:8080"
    build:
      context: .  # 현재 디렉토리에서 빌드합니다.
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - XOR_KEY=${XOR_KEY}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - SLACK_INQUIRY_WEBHOOK_URL=${SLACK_INQUIRY_WEBHOOK_URL}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_TRIAL_NUMBER=${TWILIO_TRIAL_NUMBER}
      - TZ=Asia/Seoul
    logging:
      driver: "fluentd"
      options:
        fluentd-address: fluentd:24224  # Docker Compose 내부에서는 서비스 이름으로 참조
        tag: app.log

  # Fluentd 서비스
  fluentd:
    image: fluent/fluentd:latest
    container_name: fluentd
    ports:
      - "24224:24224"
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf
    environment:
      - FLUENTD_CONF=fluent.conf
      - COMPARTMENT_ID=${COMPARTMENT_ID}  # 환경 변수로 설정
      - LOG_ID=${LOG_ID}                  # 환경 변수로 설정
      - OCI_CONFIG_FILE=${OCI_CONFIG_FILE}  # 환경 변수로 설정 (OCI 설정 파일 경로)

networks:
  default:
    driver: bridge
