spring.application.name=now_here
spring.profiles.active=dev
spring.config.import=optional:classpath:key.properties, optional:classpath:application-${spring.profiles.active}.properties
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Client origin URL
client.origin.url=https://now-here.site

# Check code properties
checkCodeMap.codeStandardMemorySize=100
checkCodeMap.codeMaxMemorySize=200

# Async thread pool properties
async.pool.core-size=5
async.pool.max-size=10
async.pool.queue-capacity=25
async.thread-name-prefix=Async-

# HikariCP connection pool settings
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# Scheduling thread pool size
scheduling.thread.pool.size=20

# Cache properties using Caffeine
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=10m

# Database connection string and credentials (environment variable references)
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


## master DB
#spring.datasource.master.jdbcUrl=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
#spring.datasource.master.username=${DB_USERNAME}
#spring.datasource.master.password=${DB_PASSWORD}

## slave DB
#spring.datasource.slave.jdbcUrl=jdbc:postgresql://${READ_DB_HOST}:${READ_DB_PORT}/${DB_NAME}
#spring.datasource.slave.username=${DB_USERNAME}
#spring.datasource.slave.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

# Custom XOR encryption properties
custom.xor.key=${XOR_KEY}

# Slack integration properties
slack.notification.webhook.url=${SLACK_WEBHOOK_URL}
slack.inquiry.webhook.url=${SLACK_INQUIRY_WEBHOOK_URL}

# Email SMTP properties
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

# Twilio API properties
twilio.account_sid=${TWILIO_ACCOUNT_SID}
twilio.auth_token=${TWILIO_AUTH_TOKEN}
twilio.trial_number=${TWILIO_TRIAL_NUMBER}

