name: Copy Issues and PRs from Private to Public

on:
  workflow_dispatch:  # 수동으로 실행 가능
  schedule:
    - cron: '0 * * * *'  # 매시간 실행

jobs:
  copy-issues-and-prs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Copy Issues and Pull Requests from Private to Public Repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRIVATE_REPO: 'now-here-5/be_now-here'
          PUBLIC_REPO: 'now-here-5/Now-Here'
        run: |
          python .github/issue_mover/copy_issues_and_prs.py
