name: Deploy to cloudtype

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}

      # PostgreSQL을 먼저 기동하는 단계
      - name: Start PostgreSQL
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: hcons/now-here
          stage: main
          yaml: |
            name: postgresql
            app: postgresql@16
            options:
              rootusername: ${{ secrets.CT_DB_USERNAME }}
              rootpassword: ${{ secrets.CT_DB_PASSWORD }}
              database: ${{ secrets.CT_DB_NAME }}
              tz: Asia/Seoul
            context:
              preset: postgresql

      # 애플리케이션을 배포하는 단계 (PostgreSQL 기동 후 실행)
      - name: Deploy Application
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: hcons/now-here
          stage: main
          yaml: |
            name: now-here-server
            app: java@17
            options:
              ports: "8080"
              env:
                # Database configuration
                - name: DB_HOST
                  value: ${{ secrets.CT_DB_HOST }}
                - name: DB_PORT
                  value: ${{ secrets.CT_DB_PORT }}
                - name: DB_NAME
                  value: ${{ secrets.CT_DB_NAME }}
                - name: DB_USERNAME
                  value: ${{ secrets.CT_DB_USERNAME }}
                - name: DB_PASSWORD
                  value: ${{ secrets.CT_DB_PASSWORD }}

                # Email configuration
                - name: MAIL_HOST
                  value: ${{ secrets.MAIL_HOST }}
                - name: MAIL_PORT
                  value: ${{ secrets.MAIL_PORT }}
                - name: MAIL_USERNAME
                  value: ${{ secrets.MAIL_USERNAME }}
                - name: MAIL_PASSWORD
                  value: ${{ secrets.MAIL_PASSWORD }}

                # Slack Webhook configuration
                - name: SLACK_WEBHOOK_URL
                  value: ${{ secrets.SLACK_WEBHOOK_URL }}
                - name: SLACK_INQUIRY_WEBHOOK_URL
                  value: ${{ secrets.SLACK_INQUIRY_WEBHOOK_URL }}

                # Encryption key
                - name: XOR_KEY
                  value: ${{ secrets.XOR_KEY }}
                
                # Twilio configuration
                - name: TWILIO_ACCOUNT_SID
                  value: ${{ secrets.TWILIO_ACCOUNT_SID }}
                - name: TWILIO_AUTH_TOKEN
                    value: ${{ secrets.TWILIO_AUTH_TOKEN }}
                - name: TWILIO_TRIAL_NUMBER 
                    value: ${{ secrets.TWILIO_TRIAL_NUMBER }}

              # Start Command를 사용하여 키 복사 후 애플리케이션 시작
              start: |
                java -Duser.timezone=Asia/Seoul -Dspring.profiles.active=prod -jar ./build/libs/now_here-0.0.1-SNAPSHOT.jar

              buildenv: []
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
